export enum ErrorCode {
  // Generic
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth
  AUTH_GOOGLE_FAILED = 'AUTH_GOOGLE_FAILED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',

  // Clips
  CLIP_NOT_FOUND = 'CLIP_NOT_FOUND',
  CLIP_ALREADY_EXISTS = 'CLIP_ALREADY_EXISTS',
  CLIP_FORBIDDEN = 'CLIP_FORBIDDEN',

  // Highlights
  HIGHLIGHT_NOT_FOUND = 'HIGHLIGHT_NOT_FOUND',
  HIGHLIGHT_FORBIDDEN = 'HIGHLIGHT_FORBIDDEN',
  CLIP_NOT_ACCESSIBLE = 'CLIP_NOT_ACCESSIBLE',

  // Follows
  FOLLOW_ALREADY_EXISTS = 'FOLLOW_ALREADY_EXISTS',
  FOLLOW_NOT_FOUND = 'FOLLOW_NOT_FOUND',
  CANNOT_FOLLOW_SELF = 'CANNOT_FOLLOW_SELF',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Tags
  TAG_NOT_FOUND = 'TAG_NOT_FOUND',

  // Personal Access Tokens
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_LIMIT_EXCEEDED = 'TOKEN_LIMIT_EXCEEDED',
}
